CREATE OR REPLACE TRIGGER TRG_BAKIM_OTOMATIK
AFTER INSERT ON BAKIM_GECMISI
FOR EACH ROW
BEGIN
    UPDATE ARACLAR SET durum = 'BAKIMDA'
    WHERE arac_id = :NEW.arac_id;
END;
/


CREATE OR REPLACE TRIGGER TRG_PLAKA_KONTROL
BEFORE INSERT OR UPDATE ON ARACLAR
FOR EACH ROW
BEGIN
    :NEW.plaka := UPPER(:NEW.plaka);
END;
/