CREATE OR REPLACE TYPE T_ARAC_ROW AS OBJECT (
    marka VARCHAR2(50),
    model VARCHAR2(50),
    plaka VARCHAR2(20),
    gunluk_ucret NUMBER
);
/

CREATE OR REPLACE TYPE T_ARAC_TAB AS TABLE OF T_ARAC_ROW;
/